/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperheroesIndexRouteImport } from './routes/superheroes/index'
import { Route as SuperheroesPaginatedRouteImport } from './routes/superheroes/paginated'
import { Route as SuperheroesCreateRouteImport } from './routes/superheroes/create'
import { Route as SuperheroesIdIndexRouteImport } from './routes/superheroes/$id/index'
import { Route as SuperheroesIdEditRouteImport } from './routes/superheroes/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperheroesIndexRoute = SuperheroesIndexRouteImport.update({
  id: '/superheroes/',
  path: '/superheroes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperheroesPaginatedRoute = SuperheroesPaginatedRouteImport.update({
  id: '/superheroes/paginated',
  path: '/superheroes/paginated',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperheroesCreateRoute = SuperheroesCreateRouteImport.update({
  id: '/superheroes/create',
  path: '/superheroes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperheroesIdIndexRoute = SuperheroesIdIndexRouteImport.update({
  id: '/superheroes/$id/',
  path: '/superheroes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperheroesIdEditRoute = SuperheroesIdEditRouteImport.update({
  id: '/superheroes/$id/edit',
  path: '/superheroes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/superheroes/create': typeof SuperheroesCreateRoute
  '/superheroes/paginated': typeof SuperheroesPaginatedRoute
  '/superheroes': typeof SuperheroesIndexRoute
  '/superheroes/$id/edit': typeof SuperheroesIdEditRoute
  '/superheroes/$id': typeof SuperheroesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/superheroes/create': typeof SuperheroesCreateRoute
  '/superheroes/paginated': typeof SuperheroesPaginatedRoute
  '/superheroes': typeof SuperheroesIndexRoute
  '/superheroes/$id/edit': typeof SuperheroesIdEditRoute
  '/superheroes/$id': typeof SuperheroesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/superheroes/create': typeof SuperheroesCreateRoute
  '/superheroes/paginated': typeof SuperheroesPaginatedRoute
  '/superheroes/': typeof SuperheroesIndexRoute
  '/superheroes/$id/edit': typeof SuperheroesIdEditRoute
  '/superheroes/$id/': typeof SuperheroesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/superheroes/create'
    | '/superheroes/paginated'
    | '/superheroes'
    | '/superheroes/$id/edit'
    | '/superheroes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/superheroes/create'
    | '/superheroes/paginated'
    | '/superheroes'
    | '/superheroes/$id/edit'
    | '/superheroes/$id'
  id:
    | '__root__'
    | '/'
    | '/superheroes/create'
    | '/superheroes/paginated'
    | '/superheroes/'
    | '/superheroes/$id/edit'
    | '/superheroes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuperheroesCreateRoute: typeof SuperheroesCreateRoute
  SuperheroesPaginatedRoute: typeof SuperheroesPaginatedRoute
  SuperheroesIndexRoute: typeof SuperheroesIndexRoute
  SuperheroesIdEditRoute: typeof SuperheroesIdEditRoute
  SuperheroesIdIndexRoute: typeof SuperheroesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superheroes/': {
      id: '/superheroes/'
      path: '/superheroes'
      fullPath: '/superheroes'
      preLoaderRoute: typeof SuperheroesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superheroes/paginated': {
      id: '/superheroes/paginated'
      path: '/superheroes/paginated'
      fullPath: '/superheroes/paginated'
      preLoaderRoute: typeof SuperheroesPaginatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superheroes/create': {
      id: '/superheroes/create'
      path: '/superheroes/create'
      fullPath: '/superheroes/create'
      preLoaderRoute: typeof SuperheroesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superheroes/$id/': {
      id: '/superheroes/$id/'
      path: '/superheroes/$id'
      fullPath: '/superheroes/$id'
      preLoaderRoute: typeof SuperheroesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superheroes/$id/edit': {
      id: '/superheroes/$id/edit'
      path: '/superheroes/$id/edit'
      fullPath: '/superheroes/$id/edit'
      preLoaderRoute: typeof SuperheroesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuperheroesCreateRoute: SuperheroesCreateRoute,
  SuperheroesPaginatedRoute: SuperheroesPaginatedRoute,
  SuperheroesIndexRoute: SuperheroesIndexRoute,
  SuperheroesIdEditRoute: SuperheroesIdEditRoute,
  SuperheroesIdIndexRoute: SuperheroesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
